# Generated by Django 4.1.1 on 2022-10-22 02:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendor_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
