# Generated by Django 4.1.1 on 2022-09-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='ad1_image',
            field=models.ImageField(null=True, upload_to='ads', verbose_name='Ad1 Image'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='ad2_image',
            field=models.ImageField(null=True, upload_to='ads', verbose_name='Ad2 Image'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='ad3_image',
            field=models.ImageField(null=True, upload_to='ads', verbose_name='Ad3 Image'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='link1',
            field=models.CharField(max_length=1500, null=True, verbose_name='Link 1'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='link2',
            field=models.CharField(max_length=1500, null=True, verbose_name='Link 2'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='link3',
            field=models.CharField(max_length=1500, null=True, verbose_name='Link 3'),
        ),
    ]
