# Generated by Django 4.1.1 on 2022-10-16 12:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mini_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Mini Decription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='About Product'),
        ),
    ]
