# Generated by Django 4.1.1 on 2022-10-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_mini_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_life',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Life'),
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rengleri Daxil Edin :'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Olculeri'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Style Elave Edin :'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='wireless',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, null=True, verbose_name='Wireless'),
        ),
    ]
