# Generated by Django 4.1.1 on 2022-10-23 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0015_product_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basket',
            field=models.ManyToManyField(blank=True, related_name='basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
