# Generated by Django 4.1.1 on 2022-10-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_tempamount_alter_basket_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tempamount',
            field=models.FloatField(default=1),
        ),
    ]
