# Generated by Django 4.1 on 2022-09-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'Buyer'), (2, 'Seller'), (3, 'Admin')], null=True, verbose_name='Duty'),
        ),
    ]
