# Generated by Django 4.1 on 2022-09-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='usertype',
        ),
    ]
