# Generated by Django 4.1 on 2022-09-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_myuser_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='company name'),
        ),
    ]
