# Generated by Django 4.1 on 2022-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_myuser_company_name_myuser_is_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_buyer',
            field=models.BooleanField(default=False, verbose_name='user buyer'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='user seller'),
        ),
    ]
