# Generated by Django 4.1.1 on 2022-09-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_myuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usertype',
            field=models.IntegerField(blank=True, choices=[(1, 'Man'), (2, 'Woman')], default=1, null=True, verbose_name='Cins'),
        ),
    ]
