# Generated by Django 4.1.1 on 2022-09-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_myuser_is_pro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'managed': True, 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
